# Generated by Django 4.2.1 on 2023-05-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Модель')),
                ('country', models.CharField(max_length=128, verbose_name='Страна происхождения')),
                ('power', models.CharField(max_length=32, verbose_name='Мощность')),
                ('drive', models.CharField(max_length=32, verbose_name='Привод')),
                ('comment', models.TextField(verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
    ]
